# -*- coding: utf-8 -*-
"""iris-eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxGT-KIw8zJMJAIFrt_-Xy_00CkBf2Mw
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

iris = pd.read_csv("iris.csv")

iris.shape

iris.columns

iris["variety"].value_counts()

iris.plot(kind = 'scatter', x= 'sepal.length', y = 'sepal.width')
plt.grid()
plt.show()

iris.plot(kind = 'scatter', x= 'petal.length', y = 'petal.width')
plt.grid()
plt.show()

#Scatter Plot:
sns.set_style('whitegrid')
sns.FacetGrid(iris, hue = 'variety') \
    .map(plt.scatter, 'sepal.length', 'sepal.width') \
    .add_legend()
plt.show()

#Pair_Plot:
sns.set_style("whitegrid")
sns.pairplot(iris, hue ='variety',size =  3)
plt.show()

iris_setosa = iris.loc[iris['variety']=='setosa']
iris_virginica= iris.loc[iris['variety']=='virginica']
iris_versicolor= iris.loc[iris['variety']=='versicolor']

plt.plot(iris_setosa['petal.length'],np.zeros_like(iris_setosa['petal.length']))
plt.plot(iris_versicolor['petal.length'],np.zeros_like(iris_versicolor['petal.length']))
plt.plot(iris_virginica['petal.length'],np.zeros_like(iris_virginica['petal.length']))
plt.show()

sns.FacetGrid(iris, hue = 'variety') \
    .map(sns.distplot,'petal.length') \
    .add_legend()
plt.show()

sns.FacetGrid(iris, hue = 'variety') \
    .map(sns.distplot,'petal.width') \
    .add_legend()
plt.show()

sns.FacetGrid(iris, hue = 'variety') \
    .map(sns.distplot,'sepal.length') \
    .add_legend()
plt.show()

sns.FacetGrid(iris, hue = 'variety') \
    .map(sns.distplot,'sepal.width') \
    .add_legend()
plt.show()

